# Configuración general de Winlogbeat
winlogbeat.event_logs:
  - name: Application
    ignore_older: 72h
  - name: Security
    ignore_older: 72h
  - name: System
    ignore_older: 72h
  - name: Setup
    ignore_older: 72h
  - name: ForwardedEvents
    ignore_older: 72h

# Configuración de la salida
# Enviamos los eventos directamente al servidor Loki en formato JSON
output.http:
  hosts: ["http://192.168.1.10:3100"]  # Dirección del servidor Loki
  path: "/loki/api/v1/push"            # API de Loki para enviar logs
  headers:
    Content-Type: application/json
  compression_level: 3                # Nivel de compresión para reducir el tamaño de los datos enviados

# Configuración de encoding (formato JSON para Loki)
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

# Configuración adicional
setup.template.settings:
  index.number_of_shards: 1

logging.level: info  # Cambia a 'debug' si necesitas depurar
logging.to_files: true
logging.files:
  path: C:/Program Files/Winlogbeat/logs
  name: winlogbeat
  keepfiles: 7
  permissions: 0644
